# Generated by Django 4.2.6 on 2023-11-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserBase', '0004_user_organization_user_workcenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='workcenter',
            new_name='work_center',
        ),
    ]
