# Generated by Django 4.2.2 on 2023-09-22 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_appellation_region_ranking_appellation_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appellation',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.region'),
        ),
    ]
