# Generated by Django 4.2.2 on 2023-09-18 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('Days', 'Days'), ('Nights', 'Nights'), ('Mids', 'Mids')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField()),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modex', models.IntegerField()),
                ('discrepancy', models.CharField(max_length=50)),
                ('text_body', models.TextField()),
                ('passdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passdown.passdown')),
            ],
        ),
    ]
