# Generated by Django 4.2.2 on 2023-10-03 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ('passdown', '0017_alter_passdown_options_alter_entry_passdown'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passdown',
            options={'ordering': ['date_time']},
        ),
        migrations.AlterField(
            model_name='entry',
            name='passdown',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.last, on_delete=django.db.models.deletion.CASCADE, to='passdown.passdown'),
        ),
    ]
