# Generated by Django 4.2.6 on 2023-11-02 22:42

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ('UserBase', '0005_rename_workcenter_user_work_center'),
        ('passdown', '0025_alter_entry_passdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='passdown',
            name='work_center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserBase.workcenter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='passdown',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.last, on_delete=django.db.models.deletion.CASCADE, to='passdown.passdown'),
        ),
    ]
