# Generated by Django 4.2.6 on 2023-11-02 23:59

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ('passdown', '0026_passdown_work_center_alter_entry_passdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='job_status',
            field=models.CharField(blank=True, choices=[('IW', 'IW'), ('M1', 'M1'), ('M3', 'M3'), ('M4', 'M4'), ('M5', 'M5'), ('M7', 'M7'), ('M8', 'M8'), ('WP', 'WP'), ('J/C', 'J/C'), ('S/O', 'S/O')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='passdown',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.last, on_delete=django.db.models.deletion.CASCADE, to='passdown.passdown'),
        ),
    ]
